#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_THEME: white
#+REVEAL_SLIDE:
#+OPTIONS: toc:nil num:nil
#+DATE: 20240216
#+AUTHOR: Eduardo Robles
#+TITLE: Quick, Easy, Malware Investigations and Threat Hunting

* Quick, Easy, Malware Investigations and Threat Hunting
Learn the basics of Malware Analysis and levarage tools like containers and virtual machines to do your analysis. Sharpen your Threat Hunting skills to better understand threats in your environment. Do all of this with free and open source tools to keep investigation internal and secure.
* About Me
- Hi! I'm Eduardo Robles I work for County of Hidalgo IT dept as a Cybersecurity Analyst III
- Founder of South Texas Linux Users Group.
- You can check out my skills on my blog or LinkedIn.
  *Bonus, I give out a lot of free advice over there*
* Agenda
1. Learn the basics of Malware Analysis
2. Learn some Threat Hunting skills
3. Small look at Reverse Engineering and Digital Forensics

* Malware Investigations
** Why do internal malware analysis?
- Existing tools Virustotal, JoeSandbox, etc.
- Protect sensitive information from 3rd parties.
- Freedom from reliance on one tool or platform.
** Malware is scary and dangerous, put in a box (container).
Malware is scary. Malware is dangerous. So it's best to analyze in a contained environment.
- Virtual Machines
- Containers (Docker, Podman, etc)
- *Read Only* shared storage
** Capturing Malware Samples
Safely moving malware around to later analyze can be daunting. Here are some pointers.
- Defang ex. https://eduardorobles.com --> hxxps://eduardorobles[.]com or =superbad.exe= --> =superbad.malz=
- Encrypted Archive with password (7zip)
- Read Only directories
- Disable network access (or simulate network access)
** REMnux
If you want easy button for malware analysis use *REMnux* as a VM or container!
** Setup REMnux in a Container
REMnux offers several [[https://docs.remnux.org/install-distro/remnux-as-a-container][container]] images as well the full REMnux distro in a container. The container technology they chose is Docker but I have chosen to use Podman. Podman seems to have better support in Windows as well as Linux. So I can have Podman running in both the Malware Analysis station and on my Windows machine. This gives me the flexibility to test on either machine or platform.
*** Install REMnux container
#+begin_src sh
podman pull docker.io/remnux/remnux-distro:focal
#+end_src
*** Run REMnux as a Transient container
#+begin_src powershell
podman run --rm -it -u remnux remnux/remnux-distro:focal bash
#+end_src
- =--rm= Remove the container after it exists (not the image)
- =-it= Connect the container to the terminal
- =-u remnux= Logged in user
- =remnux/remnux-distro:focal= Container image to use, in this case use the local image
- =bash= Login shell
** Demo
* Threat Hunting
** Malicious Traffic
- Wireshark
- iNetSim
- Firewalls
- DNS Sinkholes
* Digital Forensics
** Phishing Email Analysis
*** ClamAV
ClamAV is great to scan for malware but also can can =eml= files including email attachments.
#+begin_src sh
clamscan --debug /path/to/emailtoscan.eml
#+end_src
** Investigating a malicious link
To investigate a link REMnux offers so many awesome tools. I will cover THUG, which is a “honeyclient”. A honeyclient is a tool that mimicks the behavior of a web browser. Useful for analyzing what a link does when a user clicks on it.

*Running THUG*

#+begin_src sh
thug -u win7chrome49 "[LINKGOESHERE]"
#+end_src
Once it begins to “load” the suspicious site it executes any code that may be on the site. Once it is done running/loading the page it dumps a report. The report contains a summary of what occured plus you get any malicious artifacts that the page may have downloaded.

In one exercise I did a suspicous page downloaded an executable and I was able to run the file command from the container to find it was indeed a malicous executable.

* Conclusion

* Questions

* Thanks
