#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_THEME: white
#+REVEAL_SLIDE:
#+OPTIONS: toc:nil num:nil
#+DATE: 20240216
#+AUTHOR: Eduardo Robles
#+TITLE: Malware Investigations and Threat Hunting

* Malware Investigations and Threat Hunting

* About Me
- Hi! I'm Eduardo Robles I work for County of Hidalgo IT dept as a Cybersecurity Analyst III
- Founder of South Texas Linux Users Group.
- You can check out my skills on my blog or LinkedIn.
  *Bonus, I give out a lot of free advice over there*
* Agenda
1. Learn the basics of Malware Analysis
2. Learn some Threat Hunting skills
3. Small look at Reverse Engineering and Digital Forensics

* Malware Investigations
** Malware is scary and dangerous, put in a box (container).
Malware is scary. Malware is dangerous. So it's best to analyze in a contained environment.
- Virtual Machines
- Containers (Docker, Podman, etc)
** REMnux
If you want easy button for malware analysis use REMnux is a VM or container!
** Setup REMnux in a Container
REMnux offers several [[https://docs.remnux.org/install-distro/remnux-as-a-container][container]] images as well the full REMnux distro in a container. The container technology they chose is Docker but I have chosen to use Podamn. Podman seems to have better support in Windows as well as Linux. So I can have Podman running in both the Malware Analysis station and on my Windows machine. This gives me the flexibility to test on either machine or platform.
*** Install REMnux container
#+begin_src sh
podman pull docker.io/remnux/remnux-distro:focal
#+end_src
*** Run REMnux as a Transient container
#+begin_src powershell
podman run --rm -it -u remnux remnux/remnux-distro:focal bash
#+end_src
- =--rm= Remove the container after it exists (not the image)
- =-it= Connect the container to the terminal
- =-u remnux= Logged in user
- =remnux/remnux-distro:focal= Container image to use, in this case use the local image
- =bash= Login shell
* Threat Hunting

* Reverse Engineering

* Digital Forensics

* Conclusion

* Questions

* Thanks
