#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_THEME: white
#+REVEAL_SLIDE:
#+OPTIONS: toc:nil num:nil
#+DATE: 20250531
#+AUTHOR: Eduardo Robles
#+TITLE: Quick, Easy, Malware Investigations and Threat Hunting

* BSIDEDS RGV 2025
#+begin_center
Quick, Easy, Malware Investigations and Threat Hunting
#+end_center

* About Me
- Hi! I'm Eduardo Robles I work for County of Hidalgo IT dept as a Cybersecurity Analyst IV
- Founder of South Texas Linux Users Group.
- You can check out my skills on my blog or LinkedIn.
* Agenda
1. Learn the basics of Malware Analysis
2. Learn some Threat Hunting skills
3. Small look at Reverse Engineering and Digital Forensics
* Malware Investigations
** Why do internal malware analysis?
- Existing tools Virustotal, JoeSandbox, etc.
- Protect sensitive information from 3rd parties.
- Freedom from reliance on one tool or platform.
** Malware is scary and dangerous, put in a box (container).
Malware is scary. Malware is dangerous. So it's best to analyze in a contained environment.
- Virtual Machines
- Containers (Docker, Podman, etc)
** Working with Malware Samples
Safely moving malware around to later analyze can be daunting. Here are some pointers.
*** Defang
Take a normal hyperlink or file extention and defang it so it's not active.
- Normal
#+begin_example
https://eduardorobles.com or superbadmalware.exe
#+end_example
- Defanged
#+begin_example
hxxps://eduardorobles[.]com or superbadmalware.malz
#+end_example
*** Encrypted Archive with a Password (7zip)
Use 7zip to password encrypt an archive. This add an extra layer of protection by not allowing someone to accidently open the archive.
*** Disable network access
- You can disable network access to your malware analysis station.
- This stops malware from communicating to a C2 infrastruture.
- Or you can also simulate network traffic if you want to analyze what the malware might be trying to communicate with.
** REMnux
If you want easy button for malware analysis use *REMnux* as a VM or a container!
https://remnux.org
#+begin_quote
REMnux: A Linux Toolkit for Malware Analysis
#+end_quote

** Setup REMnux in a Container
REMnux offers several [[https://docs.remnux.org/install-distro/remnux-as-a-container][container]] images as well the full REMnux distro in a container.
- The container technology they chose is Docker but I have chosen to use Podman.
- Podman seems to have better support in Windows as well as Linux.
- So I can have Podman running in both the Malware Analysis station and on my Windows machine. This gives me the flexibility to test on either machine or platform.
*** Run REMnux container
#+begin_src sh :dir /ssh:malVM:
podman pull docker.io/remnux/remnux-distro:focal
#+end_src
*** Run REMnux as a Transient container
#+begin_src sh
  podman run \
         --rm \
         -d \
         --name malContainer \
         -v /var/home/core/SAMPLES:/home/remnux/files \
         --privileged \
         --network none \
         remnux/remnux-distro:focal
#+end_src
#+begin_notes
What the previous command did
- =--rm= Remove the container after it exists (not the image)
- =-it= Connect the container to the terminal
- =-u remnux= Logged in user (optional)
- =--privileged= Runs container with Root privileges (optional)
= =--network none= Disables any network from the container (optional)
- =remnux/remnux-distro:focal= Container image to use, in this case use the local image
- =bash= Login shell
  #+end_notes

* Demo

* Email Investigation
Let's do an email investigation and write an email report on our findings.
* Suspicious PDF Investigation
Let's investigate a suspicious file with some basic command line applications.

* Suspicious Link Investigation
Let's investigate a suspicious link with Open Source tools.
* Conclusion

* Questions

* Thanks
