* Title
I got Malware, BTW. A quick look at the rising trend of Linux Malware.
* Elevator Pitch
Malware has increasingly been spotted in new areas of the FOSS supply chain. In this talks you will hear about the latest Malware in the Arch Linux User Repository. What can be done to protect themselves plus some ideas with fostering FOSS security.
* Description
Cyber attacks specifically malware has been a recent headache for the Open Source world. Malware has increasily been spotted in new areas of the FOSS supply chain. In many ways little has changed in our perception that Linux is immune. I think it's time we changed that. In this talks you will hear about the latest Malware in the Arch Linux User Repository (AUR). What the community and enterprises can do to protect themselves. And some ideas on what the FOSS community can help with fostering FOSS security.
* Notes
I am a Cybersecurity Analyst cosplaying a Linux Sysadmin. My role has recently shifted toward deploying Linux systems and securing them. This has spurred an interest in the rise of Linux Malware and Cyberattacks.
* Tags
government, oss, security, distrubitions, cybersecurity
* Bio
Eduardo Robles works for County of Hidalgo IT department as a Cybersecurity Analyst IV. A Linux nerd interested in Information Security, Cyber Security, Open Source, tacos, and coffee. Emacs is my way of life and Screen is my serial console of choice. You'll probably catch me burning music to my Sony Minidisc or using Emacs for hacking.
